// Generated by Wrangler by running `wrangler types --experimental-include-runtime --env-interface CloudflareEnv`

interface CloudflareEnv {
	OG: KVNamespace;
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
}
